// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bacon
int bacon(std::string inputfile1, std::string outputfile1, int ssize, std::string dircc);
RcppExport SEXP _rbacon_bacon(SEXP inputfile1SEXP, SEXP outputfile1SEXP, SEXP ssizeSEXP, SEXP dirccSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type inputfile1(inputfile1SEXP);
    Rcpp::traits::input_parameter< std::string >::type outputfile1(outputfile1SEXP);
    Rcpp::traits::input_parameter< int >::type ssize(ssizeSEXP);
    Rcpp::traits::input_parameter< std::string >::type dircc(dirccSEXP);
    rcpp_result_gen = Rcpp::wrap(bacon(inputfile1, outputfile1, ssize, dircc));
    return rcpp_result_gen;
END_RCPP
}
// events
void events(double th1, double th2, double th_shift, double window, std::string outputfname1, std::string MCMCsamplesfname1, int samplesize, int K, double c0, double Dc, std::string eventprobsfname1, int depths_size);
RcppExport SEXP _rbacon_events(SEXP th1SEXP, SEXP th2SEXP, SEXP th_shiftSEXP, SEXP windowSEXP, SEXP outputfname1SEXP, SEXP MCMCsamplesfname1SEXP, SEXP samplesizeSEXP, SEXP KSEXP, SEXP c0SEXP, SEXP DcSEXP, SEXP eventprobsfname1SEXP, SEXP depths_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type th1(th1SEXP);
    Rcpp::traits::input_parameter< double >::type th2(th2SEXP);
    Rcpp::traits::input_parameter< double >::type th_shift(th_shiftSEXP);
    Rcpp::traits::input_parameter< double >::type window(windowSEXP);
    Rcpp::traits::input_parameter< std::string >::type outputfname1(outputfname1SEXP);
    Rcpp::traits::input_parameter< std::string >::type MCMCsamplesfname1(MCMCsamplesfname1SEXP);
    Rcpp::traits::input_parameter< int >::type samplesize(samplesizeSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< double >::type Dc(DcSEXP);
    Rcpp::traits::input_parameter< std::string >::type eventprobsfname1(eventprobsfname1SEXP);
    Rcpp::traits::input_parameter< int >::type depths_size(depths_sizeSEXP);
    events(th1, th2, th_shift, window, outputfname1, MCMCsamplesfname1, samplesize, K, c0, Dc, eventprobsfname1, depths_size);
    return R_NilValue;
END_RCPP
}
// depths_ageranges
NumericMatrix depths_ageranges(const NumericVector& depths, const NumericMatrix& out, const NumericVector& elbows, int n_rows, double prob);
RcppExport SEXP _rbacon_depths_ageranges(SEXP depthsSEXP, SEXP outSEXP, SEXP elbowsSEXP, SEXP n_rowsSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type depths(depthsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type out(outSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type elbows(elbowsSEXP);
    Rcpp::traits::input_parameter< int >::type n_rows(n_rowsSEXP);
    Rcpp::traits::input_parameter< double >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(depths_ageranges(depths, out, elbows, n_rows, prob));
    return rcpp_result_gen;
END_RCPP
}
// depths_ageranges_hiatus
NumericMatrix depths_ageranges_hiatus(const NumericVector& depths, const NumericMatrix& out, const NumericVector& elbows, const NumericVector& hiatus_depths, const NumericMatrix& slopes_above, const NumericMatrix& slopes_below, const NumericMatrix& elbow_above_hiatus, const NumericMatrix& elbow_below_hiatus, int n_rows, double prob);
RcppExport SEXP _rbacon_depths_ageranges_hiatus(SEXP depthsSEXP, SEXP outSEXP, SEXP elbowsSEXP, SEXP hiatus_depthsSEXP, SEXP slopes_aboveSEXP, SEXP slopes_belowSEXP, SEXP elbow_above_hiatusSEXP, SEXP elbow_below_hiatusSEXP, SEXP n_rowsSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type depths(depthsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type out(outSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type elbows(elbowsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type hiatus_depths(hiatus_depthsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type slopes_above(slopes_aboveSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type slopes_below(slopes_belowSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type elbow_above_hiatus(elbow_above_hiatusSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type elbow_below_hiatus(elbow_below_hiatusSEXP);
    Rcpp::traits::input_parameter< int >::type n_rows(n_rowsSEXP);
    Rcpp::traits::input_parameter< double >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(depths_ageranges_hiatus(depths, out, elbows, hiatus_depths, slopes_above, slopes_below, elbow_above_hiatus, elbow_below_hiatus, n_rows, prob));
    return rcpp_result_gen;
END_RCPP
}
// depths_agegrid
List depths_agegrid(const NumericVector& depths, const NumericMatrix& out, const NumericVector& elbows, int hist_n, double min_age, double max_age, int n_rows, double prob);
RcppExport SEXP _rbacon_depths_agegrid(SEXP depthsSEXP, SEXP outSEXP, SEXP elbowsSEXP, SEXP hist_nSEXP, SEXP min_ageSEXP, SEXP max_ageSEXP, SEXP n_rowsSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type depths(depthsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type out(outSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type elbows(elbowsSEXP);
    Rcpp::traits::input_parameter< int >::type hist_n(hist_nSEXP);
    Rcpp::traits::input_parameter< double >::type min_age(min_ageSEXP);
    Rcpp::traits::input_parameter< double >::type max_age(max_ageSEXP);
    Rcpp::traits::input_parameter< int >::type n_rows(n_rowsSEXP);
    Rcpp::traits::input_parameter< double >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(depths_agegrid(depths, out, elbows, hist_n, min_age, max_age, n_rows, prob));
    return rcpp_result_gen;
END_RCPP
}
// depths_agegrid_hiatus
List depths_agegrid_hiatus(const NumericVector& depths, const NumericMatrix& out, const NumericVector& elbows, const NumericVector& hiatus_depths, const NumericMatrix& slopes_above, const NumericMatrix& slopes_below, const NumericMatrix& elbow_above_hiatus, const NumericMatrix& elbow_below_hiatus, int hist_n, double min_age, double max_age, int n_rows, double prob);
RcppExport SEXP _rbacon_depths_agegrid_hiatus(SEXP depthsSEXP, SEXP outSEXP, SEXP elbowsSEXP, SEXP hiatus_depthsSEXP, SEXP slopes_aboveSEXP, SEXP slopes_belowSEXP, SEXP elbow_above_hiatusSEXP, SEXP elbow_below_hiatusSEXP, SEXP hist_nSEXP, SEXP min_ageSEXP, SEXP max_ageSEXP, SEXP n_rowsSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type depths(depthsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type out(outSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type elbows(elbowsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type hiatus_depths(hiatus_depthsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type slopes_above(slopes_aboveSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type slopes_below(slopes_belowSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type elbow_above_hiatus(elbow_above_hiatusSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type elbow_below_hiatus(elbow_below_hiatusSEXP);
    Rcpp::traits::input_parameter< int >::type hist_n(hist_nSEXP);
    Rcpp::traits::input_parameter< double >::type min_age(min_ageSEXP);
    Rcpp::traits::input_parameter< double >::type max_age(max_ageSEXP);
    Rcpp::traits::input_parameter< int >::type n_rows(n_rowsSEXP);
    Rcpp::traits::input_parameter< double >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(depths_agegrid_hiatus(depths, out, elbows, hiatus_depths, slopes_above, slopes_below, elbow_above_hiatus, elbow_below_hiatus, hist_n, min_age, max_age, n_rows, prob));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rbacon_bacon", (DL_FUNC) &_rbacon_bacon, 4},
    {"_rbacon_events", (DL_FUNC) &_rbacon_events, 12},
    {"_rbacon_depths_ageranges", (DL_FUNC) &_rbacon_depths_ageranges, 5},
    {"_rbacon_depths_ageranges_hiatus", (DL_FUNC) &_rbacon_depths_ageranges_hiatus, 10},
    {"_rbacon_depths_agegrid", (DL_FUNC) &_rbacon_depths_agegrid, 8},
    {"_rbacon_depths_agegrid_hiatus", (DL_FUNC) &_rbacon_depths_agegrid_hiatus, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_rbacon(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
