# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bacon <- function(inputfile1, outputfile1, ssize, dircc) {
    .Call('_rbacon_bacon', PACKAGE = 'rbacon', inputfile1, outputfile1, ssize, dircc)
}

events <- function(th1, th2, th_shift, window, outputfname1, MCMCsamplesfname1, samplesize, K, c0, Dc, eventprobsfname1, depths_size) {
    invisible(.Call('_rbacon_events', PACKAGE = 'rbacon', th1, th2, th_shift, window, outputfname1, MCMCsamplesfname1, samplesize, K, c0, Dc, eventprobsfname1, depths_size))
}

hist2 <- function(MCMCsamplesfname1, samplesize, c0, Dc, K, n, fout1, n_depths, dfin1) {
    invisible(.Call('_rbacon_hist2', PACKAGE = 'rbacon', MCMCsamplesfname1, samplesize, c0, Dc, K, n, fout1, n_depths, dfin1))
}

